dist: trusty
sudo: require
language: rust
cache: cargo

rust:
  - nightly

script: just test

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.5
  - export PATH="$PATH:/home/travis/.cargo/bin"
  - which diesel || cargo install diesel_cli --force
  - which just || cargo install just --force
  - echo "DATABASE_URL=postgres://postgres@localhost/nobugs" > .env
  - diesel database setup
  - diesel migration run