[package]
name = "hms_api"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[dependencies]
postgres = "0.12.0"
r2d2 = "0.7.1"
r2d2_postgres = "0.11.0"
rustless = "0.9.0"
hyper = "0.9"
iron = "0.4"
rustc-serialize = "^0.3"
valico = "1.0"